# Generated by Django 3.1.4 on 2021-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Number',
            field=models.IntegerField(default=0),
        ),
    ]
